### ISSUE TITLE
[feature] Read Pcap from Stdin

### ISSUE THREAD

**Issue by tetraf** [packetfu/packetfu#102]
It may be interesting to support reading from $stdin (i.e. in PcapFile).
Launch a tcpdump through ssh on a remote machine for live data processing on a local machine is a legit example of use.

**Comment by claudijd** [comment]
@tetraf Thanks for the suggestion!  If you'd like to work up a prototype and send us a PR we'd be happy to review it and see if it would be good fit for PacketFu.
