### ISSUE TITLE
PacketFu shell LoadError

### ISSUE THREAD

**Issue by onlyforarif** [packetfu/packetfu#103]
I have successfully installed the packetfu gem, to test the installation i try to load the shell:

$ sudo irb -r packetfu-shell.rb

It gives the following error:

`require':LoadError: cannot load such file -- packetfu-shell.rb
    1.9.3-p551 :001 >

**Comment by claudijd** [comment]
@onlyforarif the examples are not readily loadable from the gem install.

You'll want to download the source from git using a git clone.

Also, I haven't used packetfu-shell in ages and I think there is some weird path magic when you get there (we plan to fix that).  I'd recommend using an alternative example to test your install or just writing a quick script to test.

**Comment by claudijd** [comment]
@onlyforarif I did look into the PacketFu-shell stuff today and it looks like it wasn't functioning as expected. I made some tweaks in #105 that makes it functional again...

    $ rvmsudo ruby -I lib/ examples/packetfu-shell.rb 
    Password:
     _______  _______  _______  _        _______ _________ _______
    (  ____ )(  ___  )(  ____ \| \    /\(  ____ \\__   __/(  ____ \|\     /|
    | (    )|| (   ) || (    \/|  \  / /| (    \/   ) (   | (    \/| )   ( |
    | (____)|| (___) || |      |  (_/ / | (__       | |   | (__    | |   | |
    |  _____)|  ___  || |      |   _ (  |  __)      | |   |  __)   | |   | |
    | (      | (   ) || |      |  ( \ \ | (         | |   | (      | |   | |
    | )      | )   ( || (____/\|  /  \ \| (____/\   | |   | )      | (___) |
    |/       |/     \|(_______/|_/    \/(_______/   )_(   |/       (_______)
     ____________________________              ____________________________
    (                            )            (                            )
    | 01000001 00101101 01001000 )( )( )( )( )( 00101101 01000001 00100001 |
    |                            )( )( )( )( )(                            |
    (____________________________)            (____________________________)
                                   PacketFu
                 a mid-level packet manipulation library for ruby

    >>> PacketFu Shell 1.1.12.
    >>> Use $packetfu_default.config for salient networking details.
    IP:  192.168.10.173  Mac: 78:31:c1:ce:39:bc   Gateway: d8:eb:97:b1:1b:6c
    Net: 192.168.10.0                             Iface:   en0
    >>> Packet capturing/injecting enabled.
    <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
    >> pkt = TCPPacket.new
    => --EthHeader-------------------------------------------
      eth_dst      00:01:ac:00:00:00 PacketFu::EthMac     
      eth_src      00:01:ac:00:00:00 PacketFu::EthMac     
      eth_proto    0x0800            StructFu::Int16      
    --IPHeader--------------------------------------------
      ip_v         4                 Fixnum               
      ip_hl        5                 Fixnum               
      ip_tos       0                 StructFu::Int8       
      ip_len       20                StructFu::Int16      
      ip_id        0x759d            StructFu::Int16      
      ip_frag      0                 StructFu::Int16      
      ip_ttl       32                StructFu::Int8       
      ip_proto     6                 StructFu::Int8       
      ip_sum       0xffff            StructFu::Int16      
      ip_src       0.0.0.0           PacketFu::Octets     
      ip_dst       0.0.0.0           PacketFu::Octets     
    --TCPHeader-------------------------------------------
      tcp_src      64638             StructFu::Int16      
      tcp_dst      0                 StructFu::Int16      
      tcp_seq      0x72ecb473        StructFu::Int32      
      tcp_ack      0x00000000        StructFu::Int32      
      tcp_hlen     5                 PacketFu::TcpHlen    
      tcp_reserved 0                 PacketFu::TcpReserved
      tcp_ecn      0                 PacketFu::TcpEcn     
      tcp_flags    ......            PacketFu::TcpFlags   
      tcp_win      16384             StructFu::Int16      
      tcp_sum      0x4c1a            StructFu::Int16      
      tcp_urg      0                 StructFu::Int16      
      tcp_opts                       PacketFu::TcpOptions

**Comment by claudijd** [comment]
Fixed in #105
