### ISSUE TITLE
PCAP-NG Support Feedback Loop

### ISSUE THREAD

**Issue by claudijd** [packetfu/packetfu#152]
We're going to be creating a pre-release for PCAP-NG support in PacketFu soon after we land #125

I would like to use this thread to capture any community feedback for people who are interested in doing so.

Initial list of interested parties: @claudijd, @sdaubert, @bf4

**Comment by claudijd** [comment]
Code is merged in #125, working on getting gem push rights to cut this pre-release from @todb.

**Comment by todb-r7** [comment]
@claudijd, you're added as an owner now, and should be able to publish.

https://rubygems.org/profiles/claudijd

@lsanchez-r7, I'm going to warn our friends at metasploit-framework in an issue about this change, and the likelihood of getting PacketFu updates more regularly in the future.

**Comment by claudijd** [comment]
PacketFu version 1.1.12.pre (now with support for PCAP-NG) has been released for feedback.

Pre-release notes can be found here: https://github.com/packetfu/packetfu/releases/tag/version-1.1.12.pre

You can install the pre-release like so:

    $ gem install packetfu --pre
    Fetching: packetfu-1.1.12.pre.gem (100%)
    Successfully installed packetfu-1.1.12.pre
    Parsing documentation for packetfu-1.1.12.pre
    Installing ri documentation for packetfu-1.1.12.pre
    Done installing documentation for packetfu after 1 seconds
    1 gem installed

We have one example script here, which shows how to use PacketFu to convert a traditional PCAP file to PCAP-NG (https://github.com/packetfu/packetfu/blob/master/examples/pcap2pcapng.rb).

The new PCAP-NG source code can be found here (
https://github.com/packetfu/packetfu/tree/master/lib/packetfu/pcapng)

The unit-tests that excercise the new PCAP-NG code can be found here (https://github.com/packetfu/packetfu/tree/master/spec/pcapng)

Please discuss any feedback items surrounding this release in this PR.  If there is a larger discussion on a specific topic, we can create a specific issues and make mention to them here.

**Comment by claudijd** [comment]
No real feedback here, so I'm inclined to move forward with making this a release.  If people have issues, then they can submit PR/Issues and we can address them at that time in point releases.

**Comment by claudijd** [comment]
@todb mind giving me a 👍 to move forward with doing a prod release of this and get this cleared out?

**Comment by claudijd** [comment]
This has been released a while back, cleaning up this issue.
