### ISSUE TITLE
uninitialized constant PacketFu::Packet::IPv6Packet (NameError)

### ISSUE THREAD

**Issue by xqjcool1** [packetfu/packetfu#157]
When I invoke PacketFu::Packet.parse(cap.array[0]) to parse a packet
an  error occurs as below:
/usr/local/lib/ruby/gems/2.2.0/gems/packetfu-1.1.12.pre/lib/packetfu/packet.rb:47:in `parse': uninitialized constant PacketFu::Packet::IPv6Packet (NameError)
	from arpcap.rb:6:in `<main>'

**Comment by sdaubert** [comment]
@xqjcool1 try to require `packetfu/protos/ipv6` and please tell me if it removes your problem.

**Comment by claudijd** [comment]
@sdaubert @xqjcool1 I believe the issue is a namespacing problem and not a loading problem....

    2.2.3 :001 > require 'packetfu'
     => true 
    2.2.3 :002 > PacketFu::IPv6Packet
     => PacketFu::IPv6Packet 

I will send a PR shortly to fix this.

**Comment by claudijd** [comment]
@xqjcool1 this isn't released yet in gem version, but you can use the fix in master until we cut our next release.
