### ISSUE TITLE
New gem version?

### ISSUE THREAD

**Issue by normelton** [packetfu/packetfu#167]
Can we get a new gem cut on this? I've got a project blocking on fb62ce618f7fcd44718db26118322420ae9bdbf1. Namely, it seems that packet parsing is super angry since it's not loading any protocols.

Thanks!

**Comment by claudijd** [comment]
@normelton thanks, I'll see what we can do get that fix out in a released gem form.

@todb / @bcook-r7 : any objections to me cutting an official release for 1.1.13?

**Comment by busterb** [comment]
not at all. metasploit has been using the pre version for a while for the same reason.

If you guys would like, we could see about enabling R7's automatic gem build and signing infrastructure here too. It automatically versions and publishes too.

**Comment by claudijd** [comment]
@busterb let me know what's needed to enjoy the automatic/signing R7 awesome.  I'll get busy on cutting/pushing 1.1.13 now.

**Comment by claudijd** [comment]
@normelton PacketFu version 1.1.13 has been released, which should address your blocking issue.  If you have any problems let me know.

**Comment by normelton** [comment]
Thanks, works much better now!

**Comment by claudijd** [comment]
@normelton awesome, glad it worked out for ya!
