### ISSUE TITLE
Not working on RHEL/CentOS 7.x because of missing ifconfig

### ISSUE THREAD

**Issue by chrean** [packetfu/packetfu#184]
## Steps to reproduce

Using PacketFu::Utils.ifconfig() will throw an error on CentOS/RHEL 7.x because it won't find ifconfig, which is deprecated on newer RedHat-based distros.

## Expected behavior

A call to 

PacketFu::Utils.ifconfig(<anything)

e.g.

PacketFu::Utils.ifconfig(iface)

should return relevant iface data

## Current behavior

Calling 

PacketFu::Utils.ifconfig(<anything>)

will return file not found: ifconfig

### Versions

- [x ] Ruby Version (ruby -v): 2.4.1
- [ x] PacketFu Version (gem list|grep packetfu -or- git log -1): 1.1.13
- [ x] OS Version: CentOS 7.3.1611

### I installed PacketFu from:
- [ ] Git Source
- [x] Gem

**Comment by claudijd** [comment]
The ifconfig binary is a prerequisite for the PacketFu::Utils.ifconfig call.  IMO, I'm actually in favor of maybe deprecating that function at some point in favor of more programmic non-OS specific means.  If I recall, this basically existed because legacy Rubies weren't as forth coming about OS information.

That said, #ifconfig as a utility is rarely needed, and you can get a lot of this information using PacketFu::Utils.whoami?

Would you mind sharing your use case and maybe we could help you find a work around to get the necessary information without using PacketFu::Utils.ifconfig?

**Comment by claudijd** [comment]
Here's an example of running the two side-by-side...

	> require 'packetfu'
	 => true 
	> PacketFu::Utils.ifconfig
	 => {:iface=>"en0", :eth_saddr=>"ac:bc:32:85:47:3f", :eth_src=>"\xAC\xBC2\x85G?", :ip6_saddr=>"fe80::aebc:32ff:fe85:473f", :ip6_obj=>#<IPAddr: IPv6:fe80:0000:0000:0000:aebc:32ff:fe85:473f/ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff>, :ip_saddr=>"192.168.10.37", :ip_src=>"\xC0\xA8\n%", :ip4_obj=>#<IPAddr: IPv4:192.168.10.0/255.255.255.0>}
	> PacketFu::Utils.whoami?
	 => {:iface=>"en0", :pcapfile=>"/tmp/out.pcap", :eth_saddr=>"ac:bc:32:85:47:3f", :eth_src=>"\xAC\xBC2\x85G?", :ip_saddr=>"192.168.10.37", :ip_src=>3232238117, :ip_src_bin=>"\xC0\xA8\n%", :eth_dst=>"\x00`\xE0Q\xF0\b", :eth_daddr=>"00:60:e0:51:f0:08"}

**Comment by chrean** [comment]
Hi and thanks for the answer, very appreciated.

The use case was quite easy: we needed to extract the primary IP address for a given iface/eth (on Linux and if possible on Mac OS X).

So we just wrote: 

`ip=PacketFu::Utils.ifconfig(iface)[:ip_saddr]`

By looking at your second comment, using whoami in place of ifconfig should do the job anyway.

But, on my irb:

`irb(main):003:0> PacketFu::Utils.whoami?
NameError: uninitialized constant PacketFu::IPv6Packet
Did you mean?  PacketFu::Packet
	from /Users/gabriel/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/packetfu-1.1.12/lib/packetfu/packet.rb:47:in `parse'
	from /Users/gabriel/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/packetfu-1.1.12/lib/packetfu/utils.rb:148:in `block in whoami?'
	from /Users/gabriel/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
	from /Users/gabriel/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/timeout.rb:33:in `block in catch'
	from /Users/gabriel/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/timeout.rb:33:in `catch'
	from /Users/gabriel/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/timeout.rb:33:in `catch'
	from /Users/gabriel/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/timeout.rb:108:in `timeout'
	from /Users/gabriel/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/packetfu-1.1.12/lib/packetfu/utils.rb:141:in `whoami?'
	from (irb):3
	from /Users/gabriel/.rvm/rubies/ruby-2.4.1/bin/irb:11:in `<main>'`

**Comment by claudijd** [comment]
@chrean that looks like a bug that was fixed recently.  I'm going to guess you are running an outdated gem install of PacketFu.  Can you tell me what the value of 'PacketFu::VERSION' is from your IRB prompt?  I'm going to guess it's not 1.1.13, which is the latest.

**Comment by chrean** [comment]
@claudijd you are definitely right, I downgraded to 1.1.12 some days ago for other reasons and forgot to re-update. Now with 1.1.13 it's working, I think we can definitely use whoami? in place of ifconfig.

Thanks so much for your help man!

**Comment by claudijd** [comment]
@chrean I'm glad that worked for you, take care!
