### ISSUE TITLE
Update for modern Ruby compatibility

### ISSUE THREAD

**Issue by todb** [packetfu/packetfu#207]
It's quite improbable this project is compatible with Ruby 3.2.0, so we should fix that.

**Comment by adfoster-r7** [comment]
I've just put up a PR for Ruby 3.3.0-preview1 compatibility which should help close this issue out :+1:

https://github.com/packetfu/packetfu/pull/208

**Comment by todb** [comment]
So #208 does indeed seem to solve all the 3.2.0 issues, and @adfoster-r7 is a total boss for contributing this.

@claudijd if you're still active on this project, you wanna spin out a gem? I don't want to hog all the slog work. :)

**Comment by todb** [comment]
I'm a little worried that we're not splitting Ruby 2.x vs Ruby 3.x but guarding against breaking changes is, I suppose, what `semver` is for.

**Comment by adfoster-r7** [comment]
Thanks for the PR land; A version bump that follows SemVer sounds like a good idea :+1:
Will be good to get this out as a Rubygems release 🎉

**Comment by adfoster-r7** [comment]
@todb Is there anything I can help with here to get this over the line with tagging/releasing to RubyGems etc 🎉

**Comment by todb** [comment]
Sorry for the delay there. I can take a look tonight and remember how to publish gems. :) Or, @claudijd can remember before me.

**Comment by todb** [comment]
Opened #211 to deal with gem building warnings, but it seems Good Enough. About to open a PR to bump the version, then will publish the gem. Let's see what happens!
