### ISSUE TITLE
Parse Pcap-NG

### ISSUE THREAD

**Issue by todb-r7** [packetfu/packetfu#30]
Recent versions of Wireshark and TShark save in pcap-ng, not pcap format, by default. PacketFu should be able to handle this.

http://wiki.wireshark.org/Development/PcapNg

This may involve converting to Pcap first, which would be the slow way, but would ensure no nonsense (to us) metadata.

**Comment by claudijd** [comment]
Since this is going to likely be one of the bigger features added to PacketFu in some time, I've create a WIP PR #125 for this so we can bump it along until it's completed.

**Comment by claudijd** [comment]
This work was completed in #125
