### ISSUE TITLE
How to get interfaces?

### ISSUE THREAD

**Issue by emmanuelmillionaer** [packetfu/packetfu#79]
Hi, thanks for this great gem! I'm experementing on a Windows 8 with this standard code:

    def sniff(iface)
      cap = Capture.new(:iface => 'eth0', :start => true)
      cap.stream.each do |p|
        pkt = Packet.parse p
        if pkt.is_ip?
          next if pkt.ip_saddr == Utils.ifconfig(iface)[:ip_saddr]
          packet_info = [pkt.ip_saddr, pkt.ip_daddr, pkt.size, pkt.proto.last]
          puts "%-15s -> %-15s %-4d %s" % packet_info
        end
      end
     end

    sniff(iface)

But somehow i always get this error, although i opened the console as Administrator:

        Are you sure you're root? Error: C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0
        /gems/packetfu-1.1.10/lib/packetfu/capture.rb:63:in `open_live': Error opening a
        dapter: Das System kann das angegebene Gerät nicht finden. (20) (RuntimeError)
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/packetfu-1.1.1
        0/lib/packetfu/capture.rb:63:in `capture'

Next i opened Wireshark to search for the name of the Interface, on the start screen i found 'Ethernet':

![sh](https://cloud.githubusercontent.com/assets/3428184/6370388/40d6c562-bcf0-11e4-8b9f-24609a2cd9f8.png)

I tried my code with this Interface-Name again, but had no success!

What do I wrong? How can i get the correct Interface-Name? Thanks

**Comment by emmanuelmillionaer** [comment]
Sorry i already solved my problem! I had to view for the name in Wireshark 'Details' Thanks

**Comment by claudijd** [comment]
Awesome! Glad you solved your own issue.  Thanks for using PacketFu!
