### ISSUE TITLE
Release PacketFu gem: Version Questions

### ISSUE THREAD

**Issue by todb-r7** [packetfu/packetfu#90]
After the OSSM hackparty with @claudijd, feels like it's time to release a PacketFu gem bump.

I'd like to target Monday, August 17, mainly because releasing gems near a weekend is kind of a jerk move.

So, I'll bang through whatever else is assigned to me, drop Ruby 1.8 support from the docs, and bump to.. PacketFu 2.0.0? I feel like if 1.8 is dropped that's a significant API change according to [semver](http://semver.org/). OTOH, 1.8 isn't supported anywhere anymore anyway, so 1.2.0 might be more appropriate and less disruptive for anyone's gemfiles.

Thoughts on the number?

**Comment by claudijd** [comment]
1.2.0 seems the most appropriate to me.

We can probably wait on 2.x to introduce big breaking changes in interfaces/etc. as the project evolves.

**Comment by claudijd** [comment]
Additionally, it might be in our best interest to provide more regular patch releases as we find and fix bugs and accept new functionality from the community.  Having a 20 month gap in releases is perhaps a little too infrequent considering bug-fixes, features provided by the community, and the general pace of Ruby version releases.

**Comment by todb-r7** [comment]
Oh I agree wholeheartedly, sitting here after blowing through a weak promise of releasing last Monday.

I have no intention of sitting on dev versions for stupidly long times going forward. My own schedule is a little less cramped, and that should translate into more consistent PacketFu love.

**Comment by todb-r7** [comment]
Also, figure on a Monday release for real this time.

**Comment by claudijd** [comment]
:+1:

**Comment by todb** [comment]
Okay, this is done. yay.

https://github.com/packetfu/packetfu/tree/version-1.1.11
